In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
# Load first 50,000 rows

df = pd.read_csv("Reviews.csv", nrows=50000)

print("Dataset Loaded Successfully")
print("Shape:", df.shape)

Dataset Loaded Successfully
Shape: (50000, 10)


In [3]:
# Find reviews containing the word "light"

light_reviews = df[df['Text'].str.contains(r'\blight\b', case=False, na=False)]

print("Total reviews containing 'light':", len(light_reviews))

for i, review in enumerate(light_reviews['Text'].head(20)):
    print(f"\nReview {i+1}:")
    print(review)

Total reviews containing 'light': 1415

Review 1:
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 2:
A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) because only a few stores carry it in my area and they are quite a 

In [4]:
sentence_1 = "This olive oil is wonderful and very light on the stomach."

sentence_2 = "The packaging was broken and let too much light inside the box."

sentence_3 = "I prefer this brand because it is a light and healthy snack."

documents = [sentence_1, sentence_2, sentence_3]

print("Sentence 1:", sentence_1)
print("Sentence 2:", sentence_2)
print("Sentence 3:", sentence_3)

Sentence 1: This olive oil is wonderful and very light on the stomach.
Sentence 2: The packaging was broken and let too much light inside the box.
Sentence 3: I prefer this brand because it is a light and healthy snack.


In [5]:
# Vectorization

vectorizer = CountVectorizer()

document_term_matrix = vectorizer.fit_transform(documents)

dense_matrix = document_term_matrix.toarray()

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nDense Matrix:")
print(dense_matrix)

Vocabulary:
['and' 'because' 'box' 'brand' 'broken' 'healthy' 'inside' 'is' 'it' 'let'
 'light' 'much' 'oil' 'olive' 'on' 'packaging' 'prefer' 'snack' 'stomach'
 'the' 'this' 'too' 'very' 'was' 'wonderful']

Dense Matrix:
[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [6]:
# Extract vectors

vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print("Vector 1:", vec_1)
print("Vector 2:", vec_2)
print("Vector 3:", vec_3)

Vector 1: [1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
Vector 2: [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
Vector 3: [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [7]:
# Dot Product Similarities

similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)

print("Sentence 1 vs Sentence 2 Similarity:", similarity_1_2)

print("Sentence 1 vs Sentence 3 Similarity:", similarity_1_3)

Sentence 1 vs Sentence 2 Similarity: 4
Sentence 1 vs Sentence 3 Similarity: 4


In [8]:


print(f"Dot Product (Sentence 1, Sentence 2): {similarity_1_2}")

print(f"Dot Product (Sentence 1, Sentence 3): {similarity_1_3}")

Dot Product (Sentence 1, Sentence 2): 4
Dot Product (Sentence 1, Sentence 3): 4
